#!/bin/bash
#SBATCH --output=logs/out_%j.out
#SBATCH --error=logs/err_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=5
#SBATCH --partition=long

set -e

module load miniconda
source /mnt/beegfs/apps/miniconda/etc/profile.d/conda.sh
conda activate cmapf-env
echo "Conda binary: $(which conda)"
echo "Python binary: $(which python)"

echo "Running job 0699 on $(hostname)"
python scripts/run_clingo.py --map_file Instances/maps/random-128-128-20.map --scen_file Instances/scenarios/random-128-128-20/random-128-128-20-condensed-1.scen --heuristic B --priority_file Instances/Processed/random-128-128-20/random-128-128-20-condensed-1/priority10-kpath.lp
