#!/bin/bash
#SBATCH --output=logs/out_%j.out
#SBATCH --error=logs/err_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=5
#SBATCH --partition=long

set -e

module load miniconda
source /mnt/beegfs/apps/miniconda/etc/profile.d/conda.sh
conda activate cmapf-env

echo "Running job 0049 on $(hostname)"
python scripts/run_clingo.py --map_file Instances/maps/empty-128-128.map --scen_file Instances/scenarios/empty-128-128/empty-128-128-condensed-1.scen --heuristic B --priority_file Instances/Processed/empty-128-128/empty-128-128-condensed-1/priority8-kpath.lp
