#!/bin/bash
#SBATCH --output=logs/out_%j.out
#SBATCH --error=logs/err_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=5
#SBATCH --partition=long

set -e

module load miniconda
source /mnt/beegfs/apps/miniconda/etc/profile.d/conda.sh
conda activate cmapf-env

echo "Running job 1066 on $(hostname)"
python scripts/run_clingo.py --map_file Instances/maps/room-128-128-4.map --scen_file Instances/scenarios/room-128-128-4/room-128-128-4-even-11.scen --heuristic A --priority_file Instances/Processed/room-128-128-4/room-128-128-4-even-11/priority12-kpath.lp
