#!/bin/bash
#SBATCH --output=logs/out_%j.out
#SBATCH --error=logs/err_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=5
#SBATCH --partition=long

set -e

module load miniconda
source /mnt/beegfs/apps/miniconda/etc/profile.d/conda.sh
conda activate cmapf-env

echo "Running job 0469 on $(hostname)"
python scripts/run_clingo.py --map_file Instances/maps/maze-32-32-2.map --scen_file Instances/scenarios/maze-32-32-2/maze-32-32-2-condensed-1.scen --heuristic A --priority_file Instances/Processed/maze-32-32-2/maze-32-32-2-condensed-1/priority9-kpath.lp
